model_dir: /home/jupyter/experiment1-100k-original_data/original_dataset/orig_model_100K/wmt_ende_transformer

data:
  train_features_file: /home/jupyter/experiment1-100k-original_data/original_dataset/data/train.en
  train_labels_file: /home/jupyter/experiment1-100k-original_data/original_dataset/data/train.de
  eval_features_file: /home/jupyter/experiment1-100k-original_data/original_dataset/data/valid.en
  eval_labels_file: /home/jupyter/experiment1-100k-original_data/original_dataset/data/valid.de
  source_vocabulary: /home/jupyter/experiment1-100k-original_data/original_dataset/data/wmtende.vocab
  target_vocabulary: /home/jupyter/experiment1-100k-original_data/original_dataset/data/wmtende.vocab
  
train:
  save_checkpoints_steps: 10000
  train_steps: 50000
  
eval:
  external_evaluators: BLEU

infer:
  batch_size: 32